---
- name: Install required packages
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - mysql-server
      - python3-pymysql
    update_cache: yes
    state: present

- name: Ensure Apache is started and enabled
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Ensure MySQL is started and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password and switch to native password auth
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    plugin: mysql_native_password
    state: present

- name: Ensure WordPress database exists
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost

- name: Ensure WordPress DB user exists
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost

- name: Download WordPress
  get_url:
    url: "{{ wordpress_download_url }}"
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy WordPress to web root
  copy:
    src: /tmp/wordpress/
    dest: "{{ wordpress_install_dir }}"
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Set permissions for WordPress files
  file:
    path: "{{ wordpress_install_dir }}"
    recurse: yes
    owner: www-data
    group: www-data

- name: Deploy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_install_dir }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'

