---
- name: Launch EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1
    ami_id: ami-0c55b159cbfafe1f0  # Replace with a valid AMI ID in your region
    instance_type: t2.micro
    key_name: my-key               # Replace with your key pair name
    security_group: my-sg-id       # Security Group ID (e.g., sg-xxxxxxxx)
    subnet_id: subnet-xxxxxxxx     # Subnet ID to launch the instance in
    instance_name: my-ec2-instance

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        wait: yes
        count: 1
        tags:
          Environment: Test
          Name: "{{ instance_name }}"
      register: ec2

    - name: Output instance public IP
      debug:
        msg: "EC2 instance public IP is {{ ec2.instances[0].public_ip_address }}"
