---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    ec2_access_key: access_key
    ec2_secret_key: secret_key
    keypair: devops
    instance_type: t2.micro
    security_group: devops-sg
    image: ami-0e9182bc6494264a4
    region: ap-south-1
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-055a768cbd9615a2f
         assign_public_ip: yes
      register: ec2
